services:
  auth-db:
    image: postgres:15-alpine
    environment: { POSTGRES_DB: taskboard, POSTGRES_USER: admin, POSTGRES_PASSWORD: secret123 }
    ports: ["5433:5432"]
  task-db:
    image: postgres:15-alpine
    environment: { POSTGRES_DB: taskboard, POSTGRES_USER: admin, POSTGRES_PASSWORD: secret123 }
    ports: ["5434:5432"]
  user-db:
    image: postgres:15-alpine
    environment: { POSTGRES_DB: taskboard, POSTGRES_USER: admin, POSTGRES_PASSWORD: secret123 }
    ports: ["5435:5432"]
  auth-service:
    build: ./auth-service
    environment: { DATABASE_URL: "postgres://admin:secret123@auth-db:5432/taskboard", JWT_SECRET: engse207-shared-jwt-secret-set2, PORT: 3001 }
    ports: ["3001:3001"]
    depends_on: [auth-db]
  task-service:
    build: ./task-service
    environment: { DATABASE_URL: "postgres://admin:secret123@task-db:5432/taskboard", JWT_SECRET: engse207-shared-jwt-secret-set2, PORT: 3002 }
    ports: ["3002:3002"]
    depends_on: [task-db]
  user-service:
    build: ./user-service
    environment: { DATABASE_URL: "postgres://admin:secret123@user-db:5432/taskboard", JWT_SECRET: engse207-shared-jwt-secret-set2, PORT: 3003 }
    ports: ["3003:3003"]
    depends_on: [user-db]
  frontend:
    build: ./frontend
    ports: ["8080:80"]
